# Generated by scripts/release.py (release-kit) from the v2026.9.2 release — do not edit.
class Colab < Formula
  desc "Automated refactoring and project updates"
  homepage "https://github.com/grahambrooks/colab"
  version "2026.9.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/colab/releases/download/v2026.9.2/colab-v2026.9.2-aarch64-apple-darwin.tar.gz"
      sha256 "bbb1afbe9806bb28a960bb6224913d55c30b6e3f5f1295bb648add76f15a06f2"
    end
    on_intel do
      url "https://github.com/grahambrooks/colab/releases/download/v2026.9.2/colab-v2026.9.2-x86_64-apple-darwin.tar.gz"
      sha256 "04129886c43b17fdfd847aa41b087ebb83c8997d2d5206e1c5787e39e167d019"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahambrooks/colab/releases/download/v2026.9.2/colab-v2026.9.2-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "2edc10524e2425c9bdc9a12d452d83853a22229ea7cdc135c190d18385bd4233"
    end
    on_intel do
      url "https://github.com/grahambrooks/colab/releases/download/v2026.9.2/colab-v2026.9.2-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "18167d2605e356c894982f0187263c4d8d2e6d28e3667787f0dc9340d13e7e6e"
    end
  end

  def install
    bin.install "colab"
  end

  test do
    assert_path_exists bin/"colab"
  end
end
