# Generated by scripts/release.py (release-kit) from the v2026.10.1 release — do not edit.
class Colab < Formula
  desc "Automated refactoring and project updates"
  homepage "https://github.com/grahambrooks/colab"
  version "2026.10.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/colab/releases/download/v2026.10.1/colab-v2026.10.1-aarch64-apple-darwin.tar.gz"
      sha256 "d7d0da1b6d4a068d5af8e45ce76f8b6c83fa4a1a97f26f7c24aea610ea6912b9"
    end
    on_intel do
      url "https://github.com/grahambrooks/colab/releases/download/v2026.10.1/colab-v2026.10.1-x86_64-apple-darwin.tar.gz"
      sha256 "0428a2d8305db7408017893d3656e2b44d61cede2117d70feebce9e2b111b62f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahambrooks/colab/releases/download/v2026.10.1/colab-v2026.10.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "05cead45d69e4063b09f0d667e6ae864188ddea7e66f61b0651f6641fe791ebf"
    end
    on_intel do
      url "https://github.com/grahambrooks/colab/releases/download/v2026.10.1/colab-v2026.10.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "ef7473311117466a1048679606e26375b3910f91b84ad7bfc097e565c3b55293"
    end
  end

  def install
    bin.install "colab"
  end

  test do
    assert_path_exists bin/"colab"
  end
end
